### ISSUE TITLE
Don't serialize undefined properties

### ISSUE THREAD

**Issue by moll** [cognitect/transit-js#10]
``` javascript
console.log(Transit.writer("json").write({name: undefined}))
```

The above currently returns `["^ ","name",null]`.

I would argue `null` and `undefined` are different concepts. Both are falsy in the JavaScript sense, sure, but not equivalent in the semantic sense. Null could be said to be a known "unset" value (like in a tuple of `false`, `true`, `null`). Undefined, however, could be said to mean an unknown value entirely.

As Dave Herman said in **July 29 2014 TC39 Meeting Notes**:

```
- `null` represents the no-object object, just like NaN represents the no-number number
- `undefined` represents the no-value value
```

I propose to either ignore `undefined` properties in objects entirely or add an explicit tag for it. But few languages have both a `null` and `undefined`, and that would require changing the Transit protocol. Better just ignore them like `JSON.stringify` does.

**Comment by moll** [comment]
Hello again. Long time no bugfix. :)

Anywho, this is still an issue for me as `undefined` values are morphed into `null`s causing all kinds of weird behavior on the receiving end. Has there been any development here?

Who still thinks `null`s are equivalent to `undefined` values that I have to convince?

Cheers

**Comment by drarmstr** [comment]
Any known workarounds for supporting `undefined`?  You cannot simply create a handler for `undefined` (https://github.com/cognitect/transit-js/blob/master/src/com/cognitect/transit/impl/writer.js#L65)
