### ISSUE TITLE
Question about undefined handler key

### ISSUE THREAD

**Issue by tgriesser** [cognitect/transit-js#22]
I realize the blog post isn't officially associated to the repository, but it brought up a question about the behavior of an undefined handler key. The example here: http://swannodette.github.io/2014/07/30/hijacking-json/ provides the following code snippet:

```js
var wrtr = transit.writer("json-verbose", {
   handlers: transit.map([
       Immutable.Vector, VectorHandler,
       Immutable.Map, MapHandler
   ]) 
});
```

In Immutable 3, this is now `Immutable.List` rather than `Immutable.Vector`. What then results is:

```js
handlers: transit.map([
    undefined, VectorHandler,
    Immutable.Map, MapHandler
]) 
```

with the `VectorHandler` replacing the `NilHandler`, where null values are now treated as arrays, breaking when they don't have a `.forEach`, and it becomes a bit difficult to debug the actual source of the issue.

My question was, if `undefined` and `null` are both treated as `nil`, perhaps it'd be possible to throw if an `undefined` map key is encountered when defining the handlers?

**Comment by tgriesser** [comment]
I just confirmed this is still an issue as I'd mentioned but wasn't quite able to express in the ticket... it's possible to overwrite the `nil` writeHandler - by passing either `undefined` or `null` as the map key... and what ends up happening is you get an error:

```
Uncaught TypeError: Cannot read property 'forEach' of null
```

Which ends up being super difficult to trace back to the source of what went wrong. 

I'm not sure whether you should be allowed to overwrite core `writeHandlers` at all, but even if this is permitted, there is no notion of an `undefined` value in transit, so it should definitely throw on an `undefined` writeHandler?

**Comment by swannodette** [comment]
Sorry for misunderstanding this before. Fixed https://github.com/cognitect/transit-js/commit/da9c0d278a6a7155801462af749d5201b8764481 and I've cut a new release.

**Comment by tgriesser** [comment]
No problem, thanks!
