### ISSUE TITLE
Leaking a global

### ISSUE THREAD

**Issue by tgriesser** [cognitect/transit-js#24]
https://github.com/cognitect/transit-js/blob/d60905a075ae73f967b14e318af9f975b2b26fef/src/com/cognitect/transit/impl/writer.js#L207

Missing a `var` for `step` there

**Comment by swannodette** [comment]
Thanks fixed in master https://github.com/cognitect/transit-js/commit/f0dc355eb4f3f13f561cedfcb1b055e22aba7d96
