### ISSUE TITLE
Build size / include minified closure build in npm

### ISSUE THREAD

**Issue by tgriesser** [cognitect/transit-js#26]
I remembered what exactly it was that cause me to uncover the var leak in that other ticket. 

I was playing around with converting the google closure syntax into standard js syntax... mostly to get familiar with the internals of the library but also because the version released on NPM is the uncrushed version - much better for debugging but doesn't compile the namespaces nicely when using minifiers outside of closure's advanced compilation.

So I was wondering if the crushed build could be included alongside the normal source in the npm release - for those using webpack, browserify, etc. where this can be easily configured.

Nothing would need to change in the `package.json`, but it'd for optionally specifying this file as the require target for transit.

**Comment by swannodette** [comment]
@tgriesser I take it the fact that it's available in Bower is not useful for you?

**Comment by tgriesser** [comment]
Not particularly, mainly because it's a node project and so transit would be the only piece of the puzzle utilizing bower.

**Comment by tgriesser** [comment]
Oh, never mind I didn't see it has a dedicated git repository, I can just npm install / use that.
