### ISSUE TITLE
Ability to define write handler behavior on the prototype

### ISSUE THREAD

**Issue by tgriesser** [cognitect/transit-js#27]
As I was writing out the issue for defining a transformer protocol over on [transducers-js](https://github.com/cognitect-labs/transducers-js/issues/20), it occurred to me that it would be super handy if there were a similar convention for defining a write handlers in transit.

This would be great for wanting to bake in support for transit serialization without needing to require the library (since that's something you really only want to pull at the application layer).

```js
function PointHandler(x, y) {
  this.x = x
  this.y = y
}
PointHandler.prototype['@@transitWriter'] = function() {
  return {
    tag: 'point',
    rep: [this.x, this.y],
    stringRep: null
  }
}
```

Perhaps this could be the final check if a write handler is not otherwise defined for the object's constructor so folks aren't restricted to a pre-defined handler - registering an object through the traditional means would take precedence.

**Comment by swannodette** [comment]
@tgriesser thanks for bringing this up, will think about it.

**Comment by tgriesser** [comment]
What I'm actually after here can actually be implemented with `transitTag` 5bea1bbc4c5a0beeeb5904aa4c3add99c23b6a76.

I didn't see this behavior documented anywhere, is it something can be relied on?

**Comment by swannodette** [comment]
@tgriesser yep, it can be relied on! Feel free to document on the wiki. Thanks :)

**Comment by tgriesser** [comment]
Well would you look at that... it's already there :) 

https://github.com/cognitect/transit-js/wiki/Getting-Started#avoiding-duplication
