### ISSUE TITLE
XSS filtering

### ISSUE THREAD

**Issue by arnihermann** [cognitect/transit-js#31]
I'm working on a webapp that serializes state from the server via transit-js, into a variable in a `<script>` tag. If this payload contains user input, it's pretty easy to do XSS attacks, simply by making sure one of the strings that is serialized has a `</script><script>malicious code here</script>` in it.

I'm wondering if there are any recommended ways to deal with this? Could we override the `String` mapping to handle this for all strings that are passed through transit-js? I think it would be safer if we could do some kind of XSS filter transformation globally for all strings in the payload, not on some ad-hoc base per key/value of untrusted input.

I'd love to get some ideas and establish a best practice for this.

**Comment by swannodette** [comment]
@arnihermann this just seems out of scope. Why can't you sanitize the strings earlier?

**Comment by arnihermann** [comment]
I need to make sure that before I write the data into a <script> tag, that the json payload will not contain malicious string and thought to myself that before writing the data out would be the safest and least error prone way of making sure it's sanitized. But you're right, this might be completely out of scope for transit-js.

The reason we don't need to do this anywhere else in our stack is because we're using react and whenever we render a string, react makes sure that it's escaped. We're using transit-js to make ensure data types from immutable-js are preserved when we read back the application state. There might be some way to sanitize strings with immutable-js before we write the data out, I'd have to look into that. 

Do you feel this is the wrong place in the stack to sanitize strings?

**Comment by arnihermann** [comment]
I need to make sure that before I write the data into a `<script>` tag, that the json payload will not contain malicious string and thought to myself that before writing the data out would be the safest and least error prone way of making sure it's sanitized. But you're right, this might be completely out of scope for transit-js.

The reason we don't need to do this anywhere else in our stack is because we're using react and whenever we render a string, react makes sure that it's escaped. We're using transit-js to make ensure data types from immutable-js are preserved when we read back the application state. There might be some way to sanitize strings with immutable-js before we write the data out, I'd have to look into that. 

Do you feel this is the wrong place in the stack to sanitize strings?

**Comment by arnihermann** [comment]
Posted twice because apparently github doesn't escape `<script>` in comments.

**Comment by swannodette** [comment]
@arnihermann yes transit-js is a generic JavaScript library and string sanitization is really a browser specific concern.

**Comment by arnihermann** [comment]
Ok, closing this as unrelated.
