### ISSUE TITLE
cmap is a bit surprising

### ISSUE THREAD

**Issue by glenjamin** [cognitect/transit-js#33]
It's unclear to me whether this is a docs issue, a code issue, or a me-not-reading-enough issue.

When using the immutable example from https://github.com/cognitect/transit-js/wiki/Getting-Started#customizing-map--array-decoding maps of composite values to other composite values are still created as TransitMap instances.

After poking around the spec, code, docs and examples a bit, I figured out the following is needed to cover the `cmap` case:

```js
  handlers: {
    cmap: function(v) {
      var m = Immutable.Map().asMutable();
      for (var i = 0; i < v.length; i += 2) {
        m = m.set(v[i], v[i + 1]);
      }
      return m.asImmutable();
    }
  }
```

It's not clear to me from the docs why this doesn't use the mapBuilder interface.

**Comment by swannodette** [comment]
@glenjamin this is probably an oversight. Will think about it some more.

**Comment by swannodette** [comment]
Ah, this is actually just a documentation issue. The array/map builder cases are for the primitive representation on the wire. `cmap` is really it's own case you must supply.
