### ISSUE TITLE
TransitMap.keys() does not work like Map.keys()

### ISSUE THREAD

**Issue by ivan** [cognitect/transit-js#34]
`Array.from(transitMap.keys())` always returns an empty Array.  Not sure what's going on, but I'm guessing Transit iterators are not ES6 iterators?

http://cognitect.github.io/transit-js/classes/transit.html#methods_transit.map suggested that this should have worked: "Transit maps satisfy the current version of the ECMAScript 6 Map specification."

This is a fantastic library, BTW.  I am using it to export and import millions of records from a Cassandra database.

```
# node --version
v4.0.0

# node
> transitMap = require('transit-js').map()
TransitMap {}
> transitMap.set('k', 'v')
undefined
> Array.from(transitMap.keys())
[]
> es6Map = new Map();
Map {}
> es6Map.set('k', 'v')
Map { 'k' => 'v' }
> Array.from(es6Map.keys())
[ 'k' ]
```

**Comment by swannodette** [comment]
@ivan thanks for the bug report, will look into this today.

**Comment by swannodette** [comment]
Should be fixed in master as of https://github.com/cognitect/transit-js/commit/e35ce4b780646d4e11ef7367b65a0ef6baed2c67
