### ISSUE TITLE
Streamy js reader

### ISSUE THREAD

**Issue by dustingetz** [cognitect/transit-js#44]
Docs and source suggest (to my ignorant eye) that this is not possible. Is this correct? What is the best path forward for me to stream transit values out of an XHR?

**Comment by swannodette** [comment]
No idea. Is streaming JSON a thing broadly in browsers? If so I wasn't aware of it. Happy to look at something if you have links.

**Comment by dustingetz** [comment]
From a couple hours research, it's the wild west. I think I may try to implement this with the following:

streamy JSON.parse https://github.com/dscape/clarinet
streamy HTTP https://github.com/jonnyreeves/fetch-readablestream

At a glance, Clarinet is 10x slower than JSON.parse. Do you have numbers on the unreleased msgpack impl's performance?

Are there steps I should take to help this get contributed back? I would guess no, because the changes to transit look trivial.

**Comment by swannodette** [comment]
@dustingetz I researched this when we started on Transit. It just didn't look reasonable at the time and it doesn't appear anything has changed in the past couple of years.

**Comment by swannodette** [comment]
Not going to work on this so closing this for now.
