### ISSUE TITLE
Unmarshalling an object (a.k.a already JSON.parsed)

### ISSUE THREAD

**Issue by moll** [cognitect/transit-js#8]
Hey,

It's a little unclear from the examples or docs how does one unmarshal (and later marshal for that matter) an object that has already been `JSON.parse`d. I wish to use Transit for some code that does its own serializing to JSON and back.

Thanks!

**Comment by moll** [comment]
This is still a problem for me. Is it possible now to use Transit to decode an already `JSON.parse`d object? Otherwise the API is way too coupled to serialization and too coarse grained. I bet Hickey wouldn't be happy. ^_^

**Comment by swannodette** [comment]
@moll it's already possible. The `transit.decoder` factory function is a part of the public API.

**Comment by moll** [comment]
Thanks! I'll take a look. I take it's new given that you didn't suggest it back in August 2014 when I opened this issue?

It's not immediately obvious how one would use it. On the off chance you're close by now, something like this?
```javascript
var objInTransitFormat = JSON.parse(json)
var obj = Transit.decoder().decode(objInTransitFormat)
```

The `JSON.parse` bit is out of my control, hence the need to decode an already parsed object.
Thanks!

**Comment by moll** [comment]
Actually, I think `decode` has been there for some time now. I'm starting to remember and see I've even used it.

What I don't see is `encode` to get a plain object with Transit's tags back. The `marshalTop` problem I mentioned months back _seems_ still like an issue. I hope you can prove me wrong.

**Comment by swannodette** [comment]
@moll that's a different issue from the one discussed in this ticket. I see no problem with exposing a `encoder` factory fn to mirror `decoder`. Please open a new issue. Thanks.
